windowrule {
    name = float-file-picker
    match:class = xdg-desktop-portal-gtk

    float = on
    size = (monitor_w*0.6) (monitor_h*0.7)
}

windowrule {
    name = float-yazi
    match:class = org.omarchy.yazi

    float = on
    size = (monitor_w*0.6) (monitor_h*0.7)
}

windowrule {
    name = float-clipboard
    match:class = clipse

    float = on
    size = (monitor_w*0.5) (monitor_h*0.6)
}

windowrule {
    name = float-calculator
    match:class = chrome-www.desmos.com__scientific-Default
    float = on
    size = (monitor_w*0.3) (monitor_h*0.5)
}

windowrule {
    name = float-strawberry
    match:initial_title = Edit track information — Strawberry Music Player

    float = on
    size = (monitor_w*0.5) (monitor_h*0.9)
}

windowrule {
  name = pseudosmaller
  match:class = ticktick

  pseudo = on
    size = (monitor_w*0.95) (monitor_h*0.9)
}
